### ISSUE TITLE
Check which changes encompassed in https://github.com/vulcanize/go-ethereum/issues/84 are already reflected here

### ISSUE THREAD

**Issue by i-norden** [vulcanize/eth-statediff-service#21]
- [x] leaf keys for deleted values: https://github.com/vulcanize/go-ethereum/issues/59
- [x] new logs table: https://github.com/vulcanize/go-ethereum/issues/79
- [ ] code and codehash: https://github.com/vulcanize/go-ethereum/issues/90

Lower priority:
- [ ] account preimages: https://github.com/vulcanize/go-ethereum/issues/35
